# Generated by Django 5.1.2 on 2024-10-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turf',
        ),
    ]
