# Generated by Django 5.1.2 on 2024-10-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='turf_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img.png', upload_to='turfimages')),
                ('name', models.CharField(max_length=150)),
                ('game_type', models.CharField(choices=[('Football', 'Football'), ('Cricket', 'Cricket'), ('Tennis', 'Tennis')], default='Football', max_length=10)),
                ('location', models.TextField()),
                ('locaion_url', models.TextField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('discription', models.TextField()),
                ('courts', models.IntegerField()),
            ],
        ),
    ]
