# Generated by Django 5.1.2 on 2024-10-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_table',
            name='game_type',
            field=models.TextField(),
        ),
    ]
