# Generated by Django 5.1.2 on 2024-10-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfowner', '0002_alter_turf_table_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_table',
            name='rent',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
