# Generated by Django 5.1.2 on 2024-10-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfowner', '0003_turf_table_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf_table',
            name='slots',
            field=models.BooleanField(default=True),
        ),
    ]
